[build]
  publish = "income-tax-refund-blog/public"
  command = "cd ./income-tax-refund-blog && hugo --themesDir ../.. --minify"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://marvelous-crostata-5e7f99.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

