[build]
  publish = "income-tax-refund-blog/public"
  command = "cd ./income-tax-refund-blog && hugo --themesDir ../.. --minify"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://and-kal.github.io/refund-tax-income-blog-theme"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
