backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: cupper-hugo-theme/income-tax-refund-blog/static/posters
public_folder: /posters
collections:
  - name: 'Income Tax Refund - Upcoming Shows'
    label: 'Income Tax Refund - Upcoming Shows'
    folder: 'cupper-hugo-theme/income-tax-refund-blog/content/upcoming'
    create: true
    path: '{{year}}-{{month}}-{{day}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'created at', name: 'date', widget: 'datetime' }
      - { label: 'date of the show', name: 'date_show', widget: 'string' }
      - { label: 'starts at', name: 'time_show', widget: 'string' }
      - { label: 'venue', name: 'venue_show', widget: 'string' }
      - { label: 'body', name: 'body', widget: 'markdown' }
  - name: 'Income Tax Refund - Past Shows'
    label: 'Income Tax Refund - Past Shows'
    folder: 'cupper-hugo-theme/income-tax-refund-blog/content/past'
    create: true
    path: '{{year}}-{{month}}-{{day}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'created at', name: 'date', widget: 'datetime' }
      - { label: 'date of the show', name: 'date_show', widget: 'string' }
      - { label: 'starts at', name: 'time_show', widget: 'string' }
      - { label: 'venue', name: 'venue_show', widget: 'string' }
      - { label: 'body', name: 'body', widget: 'markdown' }
