backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/posters
public_folder: /posters
collections:
  - name: 'Income Tax Refund - Upcoming Shows'
    label: 'Income Tax Refund - Upcoming Shows'
    folder: 'content/upcoming'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    editor:
      preview: false
    fields:
      - { label: 'title', name: 'title', widget: 'string' }
      - { label: 'date', name: 'date', widget: 'datetime' }
      - { label: 'date_show', name: 'date_show', widget: 'date' }
      - { label: 'time_show', name: 'time_show', widget: 'time' }
      - { label: 'venue_show', name: 'venue_show', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'Income Tax Refund - Past Shows'
    label: 'Income Tax Refund - Past Shows'
    folder: 'content/past'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    editor:
      preview: false
    fields:
      - { label: 'title', name: 'title', widget: 'string' }
      - { label: 'date', name: 'date', widget: 'datetime' }
      - { label: 'date_show', name: 'date_show', widget: 'date' }
      - { label: 'time_show', name: 'time_show', widget: 'time' }
      - { label: 'venue_show', name: 'venue_show', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
